version: 2.0

jobs:
    working_directory: /go/src/github.com/katoShugo/circleci
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  
    product:
        machine: true
        steps:
            - checkout
            - run: echo "product!!"
            - run: chmod 777 ./.circleci/product.deploy.sh
            - run: bash ./.circleci/product.deploy.sh
workflows:
    version: 2
    test_and_deploy:
        jobs:
            - product:
                context: deploy-test
                filters:
                    branches:
                        only: develop